// Code generated by mockery v2.34.0. DO NOT EDIT.

package mocksensor

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockFetcher is an autogenerated mock type for the Fetcher type
type MockFetcher struct {
	mock.Mock
}

type MockFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFetcher) EXPECT() *MockFetcher_Expecter {
	return &MockFetcher_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: url
func (_m *MockFetcher) Get(url string) (*http.Response, error) {
	ret := _m.Called(url)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Response, error)); ok {
		return rf(url)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFetcher_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockFetcher_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - url string
func (_e *MockFetcher_Expecter) Get(url interface{}) *MockFetcher_Get_Call {
	return &MockFetcher_Get_Call{Call: _e.mock.On("Get", url)}
}

func (_c *MockFetcher_Get_Call) Run(run func(url string)) *MockFetcher_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFetcher_Get_Call) Return(_a0 *http.Response, _a1 error) *MockFetcher_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFetcher_Get_Call) RunAndReturn(run func(string) (*http.Response, error)) *MockFetcher_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFetcher creates a new instance of MockFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFetcher {
	mock := &MockFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
