packages:
  github.com/emiliogozo/panahon-api-go/internal/db/sqlc:
    interfaces:
      Store:
        config:
          dir: "internal/mocks/db"
          filename: "store.go"
          outpkg: "mockdb"
  github.com/emiliogozo/panahon-api-go/internal/sensor:
    interfaces:
      Fetcher:
        config:
          dir: "internal/mocks"
          filename: "fetcher.go"
          outpkg: "mocksensor"
  github.com/emiliogozo/panahon-api-go/internal/token:
    interfaces:
      Maker:
        config:
          dir: "internal/mocks/token"
          filename: "maker.go"
          outpkg: "mocktoken"
