// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/emiliogozo/panahon-api-go/internal/util"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type GlabsLoad struct {
	ID            int64              `json:"id"`
	Status        pgtype.Text        `json:"status"`
	Promo         pgtype.Text        `json:"promo"`
	TransactionID pgtype.Int4        `json:"transaction_id"`
	MobileNumber  string             `json:"mobile_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MisolStation struct {
	ID        int64 `json:"id"`
	StationID int64 `json:"station_id"`
}

type ObservationsCurrent struct {
	ID            int64              `json:"id"`
	StationID     int64              `json:"station_id"`
	Rain          pgtype.Float4      `json:"rain"`
	Temp          pgtype.Float4      `json:"temp"`
	Rh            pgtype.Float4      `json:"rh"`
	Wdir          pgtype.Float4      `json:"wdir"`
	Wspd          pgtype.Float4      `json:"wspd"`
	Srad          pgtype.Float4      `json:"srad"`
	Mslp          pgtype.Float4      `json:"mslp"`
	Tn            pgtype.Float4      `json:"tn"`
	Tx            pgtype.Float4      `json:"tx"`
	Gust          pgtype.Float4      `json:"gust"`
	RainAccum     pgtype.Float4      `json:"rain_accum"`
	Timestamp     pgtype.Timestamptz `json:"timestamp"`
	TnTimestamp   pgtype.Timestamptz `json:"tn_timestamp"`
	TxTimestamp   pgtype.Timestamptz `json:"tx_timestamp"`
	GustTimestamp pgtype.Timestamptz `json:"gust_timestamp"`
}

type ObservationsMoObservation struct {
	ID        int64              `json:"id"`
	Pres      pgtype.Float4      `json:"pres"`
	Rr        pgtype.Float4      `json:"rr"`
	Rh        pgtype.Float4      `json:"rh"`
	Temp      pgtype.Float4      `json:"temp"`
	Td        pgtype.Float4      `json:"td"`
	Wdir      pgtype.Float4      `json:"wdir"`
	Wspd      pgtype.Float4      `json:"wspd"`
	Wspdx     pgtype.Float4      `json:"wspdx"`
	Srad      pgtype.Float4      `json:"srad"`
	Hi        pgtype.Float4      `json:"hi"`
	StationID int64              `json:"station_id"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
	Wchill    pgtype.Float4      `json:"wchill"`
	Rain      pgtype.Float4      `json:"rain"`
	Tx        pgtype.Float4      `json:"tx"`
	Tn        pgtype.Float4      `json:"tn"`
	Wrun      pgtype.Float4      `json:"wrun"`
	Thwi      pgtype.Float4      `json:"thwi"`
	Thswi     pgtype.Float4      `json:"thswi"`
	Senergy   pgtype.Float4      `json:"senergy"`
	Sradx     pgtype.Float4      `json:"sradx"`
	Uvi       pgtype.Float4      `json:"uvi"`
	Uvdose    pgtype.Float4      `json:"uvdose"`
	Uvx       pgtype.Float4      `json:"uvx"`
	Hdd       pgtype.Float4      `json:"hdd"`
	Cdd       pgtype.Float4      `json:"cdd"`
	Et        pgtype.Float4      `json:"et"`
	QcLevel   int32              `json:"qc_level"`
	Wdirx     pgtype.Float4      `json:"wdirx"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ObservationsObservation struct {
	ID                 int64              `json:"id"`
	Pres               pgtype.Float4      `json:"pres"`
	Rr                 pgtype.Float4      `json:"rr"`
	Rh                 pgtype.Float4      `json:"rh"`
	Temp               pgtype.Float4      `json:"temp"`
	Td                 pgtype.Float4      `json:"td"`
	Wdir               pgtype.Float4      `json:"wdir"`
	Wspd               pgtype.Float4      `json:"wspd"`
	Wspdx              pgtype.Float4      `json:"wspdx"`
	Srad               pgtype.Float4      `json:"srad"`
	Mslp               pgtype.Float4      `json:"mslp"`
	Hi                 pgtype.Float4      `json:"hi"`
	StationID          int64              `json:"station_id"`
	Timestamp          pgtype.Timestamptz `json:"timestamp"`
	Wchill             pgtype.Float4      `json:"wchill"`
	QcLevel            int32              `json:"qc_level"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	RainTips           pgtype.Int4        `json:"rain_tips"`
	RainCumulativeTips pgtype.Int4        `json:"rain_cumulative_tips"`
}

type ObservationsStation struct {
	ID            int64              `json:"id"`
	Name          string             `json:"name"`
	Lat           pgtype.Float4      `json:"lat"`
	Lon           pgtype.Float4      `json:"lon"`
	Elevation     pgtype.Float4      `json:"elevation"`
	DateInstalled pgtype.Date        `json:"date_installed"`
	MoStationID   pgtype.Text        `json:"mo_station_id"`
	SmsSystemType pgtype.Text        `json:"sms_system_type"`
	MobileNumber  pgtype.Text        `json:"mobile_number"`
	StationType   pgtype.Text        `json:"station_type"`
	StationType2  pgtype.Text        `json:"station_type2"`
	StationUrl    pgtype.Text        `json:"station_url"`
	Status        pgtype.Text        `json:"status"`
	LoggerVersion pgtype.Text        `json:"logger_version"`
	PriorityLevel pgtype.Text        `json:"priority_level"`
	ProviderID    pgtype.Text        `json:"provider_id"`
	Province      pgtype.Text        `json:"province"`
	Region        pgtype.Text        `json:"region"`
	Address       pgtype.Text        `json:"address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	Geom          util.Point         `json:"geom"`
}

type ObservationsStationhealth struct {
	ID                int64              `json:"id"`
	Vb1               pgtype.Float4      `json:"vb1"`
	Vb2               pgtype.Float4      `json:"vb2"`
	Curr              pgtype.Float4      `json:"curr"`
	Bp1               pgtype.Float4      `json:"bp1"`
	Bp2               pgtype.Float4      `json:"bp2"`
	Cm                pgtype.Text        `json:"cm"`
	Ss                pgtype.Int4        `json:"ss"`
	TempArq           pgtype.Float4      `json:"temp_arq"`
	RhArq             pgtype.Float4      `json:"rh_arq"`
	Fpm               pgtype.Text        `json:"fpm"`
	ErrorMsg          pgtype.Text        `json:"error_msg"`
	Message           pgtype.Text        `json:"message"`
	DataCount         pgtype.Int4        `json:"data_count"`
	DataStatus        pgtype.Text        `json:"data_status"`
	Timestamp         pgtype.Timestamptz `json:"timestamp"`
	StationID         int64              `json:"station_id"`
	MinutesDifference pgtype.Int4        `json:"minutes_difference"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RoleUser struct {
	RoleID    int64              `json:"role_id"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID          `json:"id"`
	UserID       int64              `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	UserAgent    string             `json:"user_agent"`
	ClientIp     string             `json:"client_ip"`
	IsBlocked    bool               `json:"is_blocked"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type SimAccessToken struct {
	AccessToken  string             `json:"access_token"`
	Type         string             `json:"type"`
	MobileNumber string             `json:"mobile_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type SimCard struct {
	MobileNumber string             `json:"mobile_number"`
	Type         pgtype.Text        `json:"type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	Email             string             `json:"email"`
	Password          string             `json:"password"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Weatherlink struct {
	ID        int64              `json:"id"`
	StationID int64              `json:"station_id"`
	Uuid      pgtype.Text        `json:"uuid"`
	ApiKey    pgtype.Text        `json:"api_key"`
	ApiSecret pgtype.Text        `json:"api_secret"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
